---
- name: my playbook
  hosts: all
  become: true
  tasks:
  - name: multiple users
    user:
      name: '{{item}}'
      state: present
    with_items:
      - user1
      - user2
      - user3  
